# Site Settings
title: Nguyen Trong Khang Resume
description: Curriculum Vitae of khangmo@gmail.com
url: 'http://agiletech.vn'
baseurl: 'https://agiletechvn.github.io' #change it according to your repository name
about: True # set to False or comment line if you want to remove the "How to use?" in the sidebar


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
style: styles-4
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Nguyen Trong Khang
tagline: Solution Architecture
pic: https://avatars3.githubusercontent.com/u/13745269?s=460&v=4  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below
summary: "I have more than 8 years of work experience in various positions. I love coding, movies and street food</br>.
As long as your heart tells you to keep on coding and building new things, you will be young, forever."

#sidebar links
email: khangmo@gmail.com
phone: +84989032564
github: khangmo
twitter: '@khangmo1'
#Update all the sections by editing the files inside _data folder.

# uncomment the next line, if you want the education section displayed in main instead of the sidebar
#education_in_main: True

# Tracker
analytics: UA-119187154-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development

theme: jekyll-theme-cayman
